name: Gather Traffic Data via GitHub API
on:
  schedule:
    - cron: "50 23 * * 6"

jobs:
  gather_views_and_clones:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Download and upload repo views from the past 7 days to S3
        run: |
          view_name=views_$(date "+%Y-%m-%d").json &&
          curl \
              -H 'Authorization: token ${{ secrets.TRAFFIC_ACTION_TOKEN }}' \
              -H 'Accept: application/vnd.github.v3+json' \
              https://api.github.com/repos/Qbeast-io/qbeast-spark/traffic/views |
          jq -c '.views | .[7:15]' > $view_name &&
          aws s3 cp $view_name ${{ secrets.AWS_S3_TRAFFIC_BUCKET }}views/$view_name

      - name: Download and upload repo clones from the past 7 days to S3
        run: |
          clone_name=clones_$(date "+%Y-%m-%d").json &&
          curl \
              -H "Authorization:token ${{ secrets.TRAFFIC_ACTION_TOKEN }}" \
              -H "Accept:application/vnd.github.v3+json" \
              https://api.github.com/repos/Qbeast-io/qbeast-spark/traffic/clones |
          jq -c '.clones | .[7:15]' > $clone_name &&
          aws s3 cp $clone_name ${{ secrets.AWS_S3_TRAFFIC_BUCKET }}clones/$clone_name
