name: Publish Container image
on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  pull_request:
jobs:
  publish-container:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.REGISTRY_PAT }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build docker image
      run: |
        CONTAINER_VERSION="nightly-$(git rev-parse --short ${GITHUB_SHA})"
        docker build . --rm --force-rm -t ghcr.io/qbeast-io/qbeast-spark/qbeast-spark:${CONTAINER_VERSION}

    # Publish only if it is on the main branch
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Log into registry
      run: docker login ghcr.io -u "Any User" -p ${{ secrets.GITHUB_TOKEN }}
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      name: Publish docker image
      run: |
        QBEAST_SPARK_VERSION="nightly-$(git rev-parse --short ${GITHUB_SHA})"
        docker push ghcr.io/qbeast-io/qbeast-spark/qbeast-spark:${QBEAST_SPARK_VERSION}
